# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('acquisition_date', models.DateField()),
                ('asset_class', models.TextField()),
                ('serial_number', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Assets',
                'verbose_name': 'Assets',
            },
        ),
    ]
