# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
            ],
            options={
                'verbose_name': 'AssetClass',
                'verbose_name_plural': 'AssetClasses',
            },
        ),
    ]
