# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depreciation_classes', '0002_auto_20170503_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depreciationclass',
            options={'verbose_name': 'Depreciation Class', 'verbose_name_plural': 'Depreciation Classes'},
        ),
    ]
